package com.asiainfo.dbx.ln.component.dao.mybatis.mapper.mysql108.component;

import com.asiainfo.dbx.ln.component.dao.mybatis.mapper.mysql108.component.StudyExperience;
import java.util.Date;
import java.util.List;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.identity_number
     *
     * @mbggenerated
     */
    private Integer identityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.stature
     *
     * @mbggenerated
     */
    private Float stature;

    private List<StudyExperience> studyExperienceList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.identity_number
     *
     * @return the value of person.identity_number
     *
     * @mbggenerated
     */
    public Integer getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.identity_number
     *
     * @param identityNumber the value for person.identity_number
     *
     * @mbggenerated
     */
    public void setIdentityNumber(Integer identityNumber) {
        this.identityNumber = identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.sex
     *
     * @return the value of person.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.sex
     *
     * @param sex the value for person.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.birthday
     *
     * @return the value of person.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.birthday
     *
     * @param birthday the value for person.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.stature
     *
     * @return the value of person.stature
     *
     * @mbggenerated
     */
    public Float getStature() {
        return stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.stature
     *
     * @param stature the value for person.stature
     *
     * @mbggenerated
     */
    public void setStature(Float stature) {
        this.stature = stature;
    }

    public void setStudyExperienceList(List<StudyExperience> studyExperienceList) {
        this.studyExperienceList=studyExperienceList;
    }

    public List<StudyExperience> getStudyExperienceList() {
        return studyExperienceList;
    }
}