package com.asiainfo.dbx.ln.component.dao.mybatis.mapper.mysql108.component;

import java.util.Date;

public class StudyExperience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_experience.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_experience.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_experience.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_experience.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_experience.person_id
     *
     * @mbggenerated
     */
    private String personId;

    private Person person;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_experience.id
     *
     * @return the value of study_experience.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_experience.id
     *
     * @param id the value for study_experience.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_experience.school_id
     *
     * @return the value of study_experience.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_experience.school_id
     *
     * @param schoolId the value for study_experience.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_experience.start_date
     *
     * @return the value of study_experience.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_experience.start_date
     *
     * @param startDate the value for study_experience.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_experience.end_date
     *
     * @return the value of study_experience.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_experience.end_date
     *
     * @param endDate the value for study_experience.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_experience.person_id
     *
     * @return the value of study_experience.person_id
     *
     * @mbggenerated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_experience.person_id
     *
     * @param personId the value for study_experience.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    public void setPerson(Person person) {
        this.person=person;
    }

    public Person getPerson() {
        return person;
    }
}