package com.asiainfo.dbx.ln.component.dao.mybatis.mapper.mysql108.component;

import com.asiainfo.dbx.ln.component.dao.mybatis.MyBatisExample;
import com.asiainfo.dbx.ln.component.dao.mybatis.MyBatisMapper;
import com.asiainfo.dbx.ln.component.dao.mybatis.mapper.mysql108.component.StudyExperience;
import com.asiainfo.dbx.ln.component.dao.mybatis.mapper.mysql108.component.StudyExperienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyExperienceMapper extends MyBatisMapper<StudyExperience, MyBatisExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    float countByExample(MyBatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    int deleteByExample(MyBatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    int insert(StudyExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    int insertSelective(StudyExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    List<StudyExperience> selectByExample(MyBatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudyExperience record, @Param("example") MyBatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_experience
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudyExperience record, @Param("example") MyBatisExample example);
}